### ISSUE TITLE
I am not receiving notification on iOS and can't run anyother code in the background when receiving notification

### ISSUE THREAD

**Issue by irchriscott** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#10]
Hello

I am getting this error on iOS when I receive notification and it is breaking the code as no other code will run afterwards

flutter: type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, Object>'
flutter: 
#0      ZPNsEventHandlerImpl.eventListener (package:zego_zpns/src/internal/zpns_event_handler_impl.dart:50:21)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#3      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#4      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#5      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by yoer** [comment]
Is the 'Push type' for iOS Offline Push in the Zego Console not set to 'APNs'?

**Comment by yoer** [comment]
do you directly use Android Studio or Xcode to run the app for testing?

if you want to test the offline push notification feature on an iOS device, you need to publish your application to a testing platform (such as TestFlight or HockeyApp) and conduct the test, instead of running the application directly through Android Studio or Xcode. This is because iOS devices can only receive offline push notifications after the application has been published. Therefore, if you need to test the offline push notification feature, you must publish the application to a testing platform and invite testers to conduct the test.

**Comment by yoer** [comment]
the issue has been too long without a reply, so it is closed.
